### ISSUE TITLE
read a config file to disable specific middlewares

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#153]
a yaml config file named `.idrinth-api-bench.yml` should be supported, that allows deactivation of specific middlewares depending on the run mode, so that the same route configuration files can be used for all run modes:
- benchmarking
- load testing (to be developed)
- content testing (to be developed)

format example:
```yaml
bench:
- json-validator
- xml-validator
load:
- json-validator
- xml-validator
content: []
```
