### ISSUE TITLE
Split the index.css in /documentation-website

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#534]
## Context

We currently have an ever-growing index.css, that contains a lot of module specific code at the moment.

## Goal

By making the css module(page or component) specific, we reduce the complexity and reduce the chance of unintended side effects. All modular css rules need to start with a class, that describes that module, so for example:

```css
.page-example h1 {
  font-size: 10%;
}
```
Or
```css
.component-layout div {
  display: grid;
}
```
