### ISSUE TITLE
remove as much of the dark mode css as possible

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#708]
## Describe the bug

Most of the css we are using is based around variables. Dark mode is not using that, but redefining colors instead.

## Expected behavior

Check variable usage across light and dark mode and make sure that a different color is defined wherever it is required instead of having a new css block.

## Additional context

```css
.light-mode {
  /* check, rename and remove unnecessary variables here */
  --white: hsla(0deg 0% 100% / 100%);
  --light-gray: hsla(204deg 8% 76% / 100%);
  --dark-gray: hsla(0deg 0% 25% / 100%);
  --dark-green: hsla(132deg 33% 29% / 100%);
  --green: hsla(120deg 77% 36% / 100%);
  --black: hsla(0deg 0% 0% / 100%);
  --light-green: hsla(99deg 90% 36% / 100%);
  --very-dark-gray: hsla(0deg 0% 12.94% / 100%);
  --darker: hsla(0deg 0% 0% / 5%);
  --lighter: hsla(0deg 0% 100% / 5%);
}

.dark-mode {
  /* redefine variables from above here */
  --white: hsla(0deg 0% 100% / 100%);
  --light-gray: hsla(204deg 8% 76% / 100%);
  --dark-gray: hsla(0deg 0% 25% / 100%);
  --dark-green: hsla(132deg 33% 29% / 100%);
  --green: hsla(120deg 77% 36% / 100%);
  --black: hsla(0deg 0% 0% / 100%);
  --light-green: hsla(99deg 90% 36% / 100%);
  --very-dark-gray: hsla(0deg 0% 12.94% / 100%);
  --darker: hsla(0deg 0% 0% / 5%);
  --lighter: hsla(0deg 0% 100% / 5%);
}
```
