### ISSUE TITLE
lighhouse check has to use nginx for more resonable performance scores

### ISSUE THREAD

**Issue by Idrinth** [Idrinth/api-bench#953]
## Context

Right now nodjs is used, leading to way worse performance scores than we really have.

## Project

Files:
- [documentation-website.lighthouse-check.yml](https://github.com/Idrinth/api-bench/blob/the-one/.github/workflows/documentation-website.lighthouse-check.yml)
- [lighthouse-report.js](https://github.com/Idrinth/api-bench/blob/the-one/documentation-website/tools/lighthouse-report.js)

**Comment by itsmacr8** [comment]
After 2 hours of reading, I got to this position. Am I heading towards the right dir, @Idrinth?

```yml
name: documentation-website lighthouse check
on:
  push:
    branches:
    - the-one
    paths:
      - 'documentation-website/**.ts'
      - 'documentation-website/**.tsx'
      - 'documentation-website/**.js'
      - 'documentation-website/**.cjs'
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.lighthouse-check.yml'
  pull_request:
    branches:
    - the-one
    paths:
      - 'documentation-website/**.ts'
      - 'documentation-website/**.tsx'
      - 'documentation-website/**.js'
      - 'documentation-website/**.cjs'
      - 'documentation-website/package-lock.json'
      - '.github/workflows/documentation-website.lighthouse-check.yml'
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        queries: security-and-quality
        source-root: documentation-website
    - name: Install Nginx
      run: sudo apt-get update && sudo apt-get install -y nginx
    - name: Configure Nginx
      run: |
        # Replace the default Nginx configuration with your own
        sudo cp ./nginx.conf /etc/nginx/sites-available/default
        sudo systemctl restart nginx
    - name: Run Lighthouse Check
      run: |
        cd documentation-website && npm install
        cd documentation-website && npm run lighthouse
```

NGinx

```conf
# User and worker settings
user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

# Events block for handling connections
events {
    worker_connections 768;
    # multi_accept on;
}

# HTTP block for handling HTTP requests
http {
    # Basic Settings
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    server_tokens off;

    # Include MIME types
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # SSL Settings
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
    ssl_prefer_server_ciphers on;

    # Logging Settings
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";

    # Virtual Host Configs
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*;

    # Reverse proxy configuration
    server {
        listen 80;
        # Server name can be domain or IP
        server_name idrinth-api-ben.ch;

        location / {
            # Proxy pass to the Node.js application
            proxy_pass http://localhost:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
```
